# Generated by Django 3.2.8 on 2021-11-17 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CumRap',
            fields=[
                ('maCumRap', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tenCumRap', models.CharField(max_length=50)),
                ('diaChi', models.CharField(max_length=100)),
                ('hinhAnh', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='HeThongRap',
            fields=[
                ('maHeThongRap', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tenHeThongRap', models.CharField(max_length=50)),
                ('biDanh', models.CharField(max_length=50)),
                ('logo', models.FileField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Phim',
            fields=[
                ('maPhim', models.IntegerField(primary_key=True, serialize=False)),
                ('tenPhim', models.CharField(max_length=50)),
                ('biDanh', models.CharField(max_length=50)),
                ('trailer', models.TextField()),
                ('hinhAnh', models.FileField(upload_to='images')),
                ('moTa', models.TextField()),
                ('maNhom', models.TextField()),
                ('ngayKhoiChieu', models.DateTimeField()),
                ('danhGia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rap',
            fields=[
                ('maRap', models.IntegerField(primary_key=True, serialize=False)),
                ('tenRap', models.CharField(max_length=10)),
                ('cumRap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.cumrap')),
            ],
        ),
        migrations.CreateModel(
            name='lichChieuPhim',
            fields=[
                ('maLichChieu', models.IntegerField(primary_key=True, serialize=False)),
                ('ngayChieuGioChieu', models.DateTimeField()),
                ('giaVe', models.IntegerField()),
                ('thoiLuong', models.IntegerField()),
                ('phim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.phim')),
                ('rap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.rap')),
            ],
        ),
        migrations.AddField(
            model_name='cumrap',
            name='heThongRap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.hethongrap'),
        ),
    ]
