# Generated by Django 3.2.8 on 2021-11-17 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cumrap',
            name='hinhAnh',
        ),
    ]
