# Generated by Django 3.2.8 on 2021-11-20 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_remove_cumrap_hinhanh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cumrap',
            name='heThongRap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cumrap', to='movie.hethongrap'),
        ),
        migrations.AlterField(
            model_name='lichchieuphim',
            name='phim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lichChieu', to='movie.phim'),
        ),
        migrations.AlterField(
            model_name='lichchieuphim',
            name='rap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lichChieu', to='movie.rap'),
        ),
        migrations.AlterField(
            model_name='rap',
            name='cumRap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rap', to='movie.cumrap'),
        ),
        migrations.CreateModel(
            name='Ghe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maGhe', models.IntegerField()),
                ('tenGhe', models.CharField(max_length=2)),
                ('loaiGhe', models.CharField(max_length=10)),
                ('stt', models.CharField(max_length=2)),
                ('giaVe', models.IntegerField()),
                ('daDat', models.BooleanField()),
                ('taiKhoanNguoiDat', models.CharField(max_length=20)),
                ('lichChieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ghe', to='movie.lichchieuphim')),
            ],
        ),
    ]
