# Generated by Django 3.2.8 on 2021-11-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20211120_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ghe',
            name='id',
        ),
        migrations.AlterField(
            model_name='ghe',
            name='maGhe',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
