# Generated by Django 3.2.8 on 2021-11-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20211120_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghe',
            name='taiKhoanNguoiDat',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
