# Generated by Django 3.2.8 on 2021-11-20 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_alter_ghe_taikhoannguoidat'),
    ]

    operations = [
        migrations.AddField(
            model_name='hethongrap',
            name='phim',
            field=models.ManyToManyField(related_name='heThongRap', to='movie.Phim'),
        ),
    ]
