# Generated by Django 3.2.8 on 2021-11-20 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_hethongrap_phim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hethongrap',
            name='phim',
        ),
        migrations.AddField(
            model_name='cumrap',
            name='phim',
            field=models.ManyToManyField(related_name='cumRap', to='movie.Phim'),
        ),
    ]
