# Generated by Django 3.2.8 on 2021-11-20 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_remove_cumrap_phim'),
    ]

    operations = [
        migrations.AddField(
            model_name='cumrap',
            name='phim',
            field=models.ManyToManyField(related_name='cumRap', to='movie.Phim'),
        ),
    ]
