# Generated by Django 3.2.8 on 2021-11-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_nguoidung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nguoidung',
            name='soDt',
            field=models.CharField(max_length=15),
        ),
    ]
