# Generated by Django 3.2.8 on 2021-11-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_alter_nguoidung_sodt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghe',
            name='stt',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='ghe',
            name='tenGhe',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterUniqueTogether(
            name='nguoidung',
            unique_together={('ID', 'taiKhoan')},
        ),
    ]
