# Generated by Django 3.2.8 on 2021-11-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_auto_20211122_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='phim',
            name='daoDien',
            field=models.TextField(default='Add in =)))'),
        ),
        migrations.AddField(
            model_name='phim',
            name='dienVien',
            field=models.TextField(default='Add in =)))'),
        ),
        migrations.AddField(
            model_name='phim',
            name='format',
            field=models.TextField(default='Add in =)))'),
        ),
        migrations.AddField(
            model_name='phim',
            name='theLoai',
            field=models.TextField(default='Add in =)))'),
        ),
        migrations.AlterField(
            model_name='phim',
            name='danhGia',
            field=models.IntegerField(default='Add in =)))'),
        ),
    ]
