# Generated by Django 3.2.8 on 2021-11-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_auto_20211128_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phim',
            name='danhGia',
            field=models.IntegerField(),
        ),
    ]
