# Generated by Django 3.2.8 on 2021-11-27 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0014_alter_phim_danhgia'),
    ]

    operations = [
        migrations.AddField(
            model_name='phim',
            name='thoiLuong',
            field=models.IntegerField(default=0),
        ),
    ]
