# Generated by Django 3.2.8 on 2021-11-27 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0015_phim_thoiluong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phim',
            name='ngayKhoiChieu',
            field=models.DateField(),
        ),
    ]
