# Generated by Django 3.2.8 on 2021-11-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0016_alter_phim_ngaykhoichieu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phim',
            name='ngayKhoiChieu',
            field=models.DateTimeField(),
        ),
    ]
