# Generated by Django 3.2.8 on 2022-04-17 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0017_alter_phim_ngaykhoichieu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cumrap',
            name='phim',
        ),
        migrations.AlterField(
            model_name='phim',
            name='daoDien',
            field=models.TextField(default='Add in'),
        ),
        migrations.AlterField(
            model_name='phim',
            name='dienVien',
            field=models.TextField(default='Add in'),
        ),
        migrations.AlterField(
            model_name='phim',
            name='format',
            field=models.TextField(default='Add in'),
        ),
        migrations.AlterField(
            model_name='phim',
            name='theLoai',
            field=models.TextField(default='Add in'),
        ),
        migrations.CreateModel(
            name='LichSuDatVe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taiKhoanNguoiDat', models.CharField(max_length=20, null=True)),
                ('giaVe', models.IntegerField()),
                ('danhSachMaGhe', models.TextField()),
                ('maQR', models.CharField(max_length=30)),
                ('lichChieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datVe', to='movie.lichchieuphim')),
            ],
        ),
    ]
