# Generated by Django 3.2.8 on 2022-04-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0018_auto_20220417_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lichsudatve',
            name='maQR',
            field=models.UUIDField(),
        ),
    ]
