# Generated by Django 3.2.8 on 2022-04-17 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0019_alter_lichsudatve_maqr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lichsudatve',
            name='id',
        ),
        migrations.AlterField(
            model_name='lichsudatve',
            name='maQR',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
