# Generated by Django 3.2.8 on 2022-04-17 03:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0020_auto_20220417_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lichsudatve',
            name='maQR',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
