# Generated by Django 3.2.8 on 2022-04-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0021_alter_lichsudatve_maqr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lichsudatve',
            name='taiKhoanNguoiDat',
            field=models.CharField(max_length=20),
        ),
    ]
