# Generated by Django 3.2.8 on 2022-04-17 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0022_alter_lichsudatve_taikhoannguoidat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nguoidung',
            old_name='matKhau',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='nguoidung',
            old_name='taiKhoan',
            new_name='username',
        ),
        migrations.AlterUniqueTogether(
            name='nguoidung',
            unique_together={('ID', 'username')},
        ),
    ]
