# Generated by Django 3.2.8 on 2022-04-17 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0023_auto_20220417_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nguoidung',
            old_name='password',
            new_name='matKhau',
        ),
        migrations.RenameField(
            model_name='nguoidung',
            old_name='username',
            new_name='taiKhoan',
        ),
        migrations.AlterUniqueTogether(
            name='nguoidung',
            unique_together={('ID', 'taiKhoan')},
        ),
    ]
