# Generated by Django 3.2.8 on 2022-04-17 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0024_auto_20220417_1441'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NguoiDung',
        ),
    ]
