# Generated by Django 3.2.8 on 2022-04-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0025_delete_nguoidung'),
    ]

    operations = [
        migrations.AddField(
            model_name='lichsudatve',
            name='isValid',
            field=models.BooleanField(default=True),
        ),
    ]
