# Generated by Django 3.2.8 on 2022-04-29 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0026_lichsudatve_isvalid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lichsudatve',
            name='lichChieu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lichChieu', to='movie.lichchieuphim'),
        ),
    ]
